-- ==============================
-- BookWise Release B1.0
-- Re-runnable Clean Setup Script
-- ==============================

CREATE DATABASE IF NOT EXISTS bookwise;
USE bookwise;

-- ------------------------------
-- 1. DROP CHILD TABLES FIRST
-- ------------------------------
DROP TABLE IF EXISTS USER_BOOKSHELF;
DROP TABLE IF EXISTS BOOK_RATING;
DROP TABLE IF EXISTS BOOK_COMMENT;
DROP TABLE IF EXISTS USER_AUTHORITY;

-- ------------------------------
-- 2. DROP PARENT TABLES
-- ------------------------------
DROP TABLE IF EXISTS BOOK_ENCOUNTER;
DROP TABLE IF EXISTS AUTHORITY;
DROP TABLE IF EXISTS BOOK_WISE_USER;

-- ------------------------------
-- 3. CREATE BOOK_WISE_USER
-- ------------------------------
CREATE TABLE BOOK_WISE_USER (
    USER_ID INT(11) NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(100) DEFAULT NULL,
    USER_PASSWORD VARCHAR(255) DEFAULT NULL,
    AGE INT(11) DEFAULT NULL,
    GENDER VARCHAR(50) DEFAULT NULL,
    MAIN_LANGUAGE VARCHAR(50) DEFAULT NULL,
    USER_EMAIL VARCHAR(255) DEFAULT NULL,
    USER_PHONE_NUMBER VARCHAR(255) DEFAULT NULL,
    USER_TYPE VARCHAR(255) DEFAULT NULL,
    PROFILE_PICTURE_PATH VARCHAR(500) DEFAULT NULL,
    MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL,
    MODIFIED_BY VARCHAR(255) DEFAULT NULL,
    STREET VARCHAR(255) DEFAULT NULL,
    CITY VARCHAR(255) DEFAULT NULL,
    STATE VARCHAR(255) DEFAULT NULL,
    ZIP_CODE VARCHAR(255) DEFAULT NULL,
    DESCRIPTION VARCHAR(1000) DEFAULT NULL,
    EMAIL_VERIFIED TINYINT(1) DEFAULT 0,
    VERIFICATION_TOKEN VARCHAR(255) DEFAULT NULL,
    LOGIN_USER_ID VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (USER_ID),
    UNIQUE KEY UK_USER_EMAIL (USER_EMAIL),
    UNIQUE KEY UK_USER_PHONE (USER_PHONE_NUMBER),
    UNIQUE KEY UK_LOGIN_USER_ID (LOGIN_USER_ID)
);

-- ------------------------------
-- 4. CREATE AUTHORITY
-- ------------------------------
CREATE TABLE AUTHORITY (
    AUTHORITY_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHORITY_NAME VARCHAR(255) NOT NULL
);

-- ------------------------------
-- 5. CREATE USER_AUTHORITY
-- ------------------------------
CREATE TABLE USER_AUTHORITY (
    USER_ID INT NOT NULL,
    AUTHORITY_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, AUTHORITY_ID),
    FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID),
    FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY(AUTHORITY_ID)
);

-- ------------------------------
-- 6. CREATE BOOK_ENCOUNTER
-- ------------------------------
CREATE TABLE BOOK_ENCOUNTER (
    BOOK_ENCOUNTER_ID INT(11) NOT NULL AUTO_INCREMENT,
    BOOK_TITLE VARCHAR(255) DEFAULT NULL,
    BOOK_AUTHOR VARCHAR(255) DEFAULT NULL,
    BOOK_ISBN_NUMBER VARCHAR(50) DEFAULT NULL,
    BOOK_PRICE VARCHAR(50) DEFAULT NULL,
    BOOK_PAGE_NUMBER VARCHAR(50) DEFAULT NULL,
    BOOK_CATEGORY VARCHAR(100) DEFAULT NULL,
    PUBLICATION_DATE DATE DEFAULT NULL,
    BOOK_LANGUAGE VARCHAR(50) DEFAULT NULL,
    BOOK_DESCRIPTION TEXT DEFAULT NULL,
    PDF_PATH VARCHAR(255) DEFAULT NULL,
    FRONT_PAGE_IMAGE_PATH VARCHAR(255) DEFAULT NULL,
    UPLOADED_BY_NAME VARCHAR(255) DEFAULT NULL,
    UPDATED_BY_ID VARCHAR(255) DEFAULT NULL,
    UPLOADED_TIME TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (BOOK_ENCOUNTER_ID)
);

-- ------------------------------
-- 7. CREATE BOOK_COMMENT
-- ------------------------------
CREATE TABLE BOOK_COMMENT (
    COMMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOOK_ENCOUNTER_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    COMMENT_TEXT VARCHAR(2000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_COMMENT_BOOK FOREIGN KEY (BOOK_ENCOUNTER_ID)
        REFERENCES BOOK_ENCOUNTER(BOOK_ENCOUNTER_ID),
    CONSTRAINT FK_COMMENT_USER FOREIGN KEY (USER_ID)
        REFERENCES BOOK_WISE_USER(USER_ID)
);

-- ------------------------------
-- 8. CREATE BOOK_RATING
-- ------------------------------
CREATE TABLE BOOK_RATING (
    RATING_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    RATING_VALUE INT NOT NULL,
    USER_ID INT NOT NULL,
    BOOK_ENCOUNTER_ID INT NOT NULL,
    RATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_RATING_USER FOREIGN KEY (USER_ID)
        REFERENCES BOOK_WISE_USER(USER_ID),
    CONSTRAINT FK_RATING_BOOK FOREIGN KEY (BOOK_ENCOUNTER_ID)
        REFERENCES BOOK_ENCOUNTER(BOOK_ENCOUNTER_ID),
    CONSTRAINT UQ_USER_BOOK_RATING UNIQUE (USER_ID, BOOK_ENCOUNTER_ID)
);

-- ------------------------------
-- 9. CREATE USER_BOOKSHELF
-- ------------------------------
CREATE TABLE USER_BOOKSHELF (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    BOOK_ENCOUNTER_ID INT NOT NULL,
    ADDED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NOTES TEXT,
    STATUS ENUM('ACTIVE', 'REMOVED') DEFAULT 'ACTIVE',
    READING_PROGRESS INT DEFAULT 0,
    LAST_READ_PAGE INT DEFAULT NULL,
    TOTAL_PAGES INT DEFAULT NULL,
    LAST_READ_DATE TIMESTAMP DEFAULT NULL,
    TOTAL_READING_TIME BIGINT DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID),
    FOREIGN KEY (BOOK_ENCOUNTER_ID) REFERENCES BOOK_ENCOUNTER(BOOK_ENCOUNTER_ID),
    UNIQUE KEY UNIQUE_USER_BOOK (USER_ID, BOOK_ENCOUNTER_ID)
);

-- ------------------------------
-- 10. INSERT MASTER DATA (SAFE)
-- ------------------------------
INSERT INTO AUTHORITY (AUTHORITY_NAME)
SELECT 'ROLE_USER'
WHERE NOT EXISTS (
    SELECT 1 FROM AUTHORITY WHERE AUTHORITY_NAME = 'ROLE_USER'
);

INSERT INTO AUTHORITY (AUTHORITY_NAME)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (
    SELECT 1 FROM AUTHORITY WHERE AUTHORITY_NAME = 'ROLE_ADMIN'
);

INSERT INTO AUTHORITY (AUTHORITY_NAME)
SELECT 'ROLE_SUPERADMIN'
WHERE NOT EXISTS (
    SELECT 1 FROM AUTHORITY WHERE AUTHORITY_NAME = 'ROLE_SUPERADMIN'
);
