logging.level.org.springframework.security=DEBUG
bookwise.storage.path=C:/usr/local/bookWiseFile
bookwise.app.base-url=http://localhost:8080/bookwise

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.resource=DEBUG

# Add logging for BookDflipImpl
logging.level.com.bookWise.dflip.impl=DEBUG
logging.level.com.bookWise.dflip.impl.BookDflipImpl=DEBUG

JDBC_DATABASE_URL=jdbc:mysql://localhost:3306/bookwise
JDBC_DATABASE_USERNAME=root
JDBC_DATABASE_PASSWORD=seaface
JDBC_DATABASE_DRIVER=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
