logging.level.org.springframework.security=DEBUG
bookwise.storage.path=C:/usr/local/bookWiseFile

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.resource=DEBUG

# Add logging for BookDflipImpl
logging.level.com.bookWise.dflip.impl=DEBUG
logging.level.com.bookWise.dflip.impl.BookDflipImpl=DEBUG
