use bookwise;

DROP TABLE IF EXISTS BOOK_WISE_USER;
CREATE TABLE BOOK_WISE_USER(
    USER_ID INT(11) NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(100) DEFAULT NULL,
    USER_PASSWORD  VARCHAR(100) DEFAULT NULL,
    AGE INT(11) DEFAULT NULL,
    GENDER  VARCHAR(10) DEFAULT NULL,
    MAIN_LANGUAGE VARCHAR(10) DEFAULT NULL,
    USER_EMAIL VARCHAR(50) DEFAULT NULL,
    USER_PHONE_NUMBER VARCHAR(50) DEFAULT NULL,
    USER_TYPE VARCHAR(50) DEFAULT NULL,
    PROFILE_PICTURE_PATH VARCHAR(500) DEFAULT NULL,
    MODIFIED_DATE TIMESTAMP DEFAULT NULL,
    MODIFIED_BY VARCHAR(50) DEFAULT NULL,
    STREET VARCHAR(50) DEFAULT NULL,
    CITY VARCHAR(50) DEFAULT NULL,
    STATE VARCHAR(50) DEFAULT NULL,
    ZIP_CODE VARCHAR(50) DEFAULT NULL,
    DESCRIPTION VARCHAR(1000) DEFAULT NULL,
    PRIMARY KEY (USER_ID)
);

DROP TABLE IF EXISTS AUTHORITY;
CREATE TABLE AUTHORITY (
    AUTHORITY_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHORITY_NAME VARCHAR(255) NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID)
);

DROP TABLE IF EXISTS USER_AUTHORITY;
CREATE TABLE USER_AUTHORITY (
    USER_ID INT,
    AUTHORITY_ID INT,
    PRIMARY KEY (USER_ID, AUTHORITY_ID),
    FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID),
    FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY(AUTHORITY_ID)
);

INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);  -- Assuming USER_ID 1 and AUTHORITY_ID 1 for ROLE_USER

DROP TABLE IF EXISTS BOOK_ENCOUNTER;
CREATE TABLE BOOK_ENCOUNTER (
    BOOK_ENCOUNTER_ID INT(11) NOT NULL AUTO_INCREMENT,
    BOOK_TITLE VARCHAR(255) DEFAULT NULL,
    BOOK_AUTHOR VARCHAR(255) DEFAULT NULL,
    BOOK_ISBN_NUMBER VARCHAR(50) DEFAULT NULL,
    BOOK_PRICE VARCHAR(50) DEFAULT NULL,
    BOOK_PAGE_NUMBER VARCHAR(50) DEFAULT NULL,
    BOOK_CATEGORY VARCHAR(100) DEFAULT NULL,
    PUBLICATION_DATE DATE DEFAULT NULL,
    BOOK_LANGUAGE VARCHAR(50) DEFAULT NULL,
    BOOK_DESCRIPTION TEXT DEFAULT NULL,
    PDF_PATH VARCHAR(255) DEFAULT NULL,
    FRONT_PAGE_IMAGE_PATH VARCHAR(255) DEFAULT NULL,
    UPLOADED_BY_NAME VARCHAR(255) DEFAULT NULL,
    UPDATED_BY_ID VARCHAR(255) DEFAULT NULL,
    UPLOADED_TIME TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (BOOK_ENCOUNTER_ID)
);

INSERT INTO authority (AUTHORITY_ID, AUTHORITY_NAME) VALUES (3, 'ROLE_SUPERADMIN');

DROP TABLE IF EXISTS BOOK_COMMENT;
CREATE TABLE BOOK_COMMENT (
    COMMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOOK_ENCOUNTER_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    COMMENT_TEXT VARCHAR(2000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_COMMENT_BOOK FOREIGN KEY (BOOK_ENCOUNTER_ID) REFERENCES BOOK_ENCOUNTER(BOOK_ENCOUNTER_ID),
    CONSTRAINT FK_COMMENT_USER FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID)
);

DROP TABLE IF EXISTS BOOK_RATING;
CREATE TABLE BOOK_RATING (
    RATING_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    RATING_VALUE INT NOT NULL,
    USER_ID INT NOT NULL,
    BOOK_ENCOUNTER_ID INT NOT NULL,
    RATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_RATING_USER FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID),
    CONSTRAINT FK_RATING_BOOK_ENCOUNTER FOREIGN KEY (BOOK_ENCOUNTER_ID) REFERENCES BOOK_ENCOUNTER(BOOK_ENCOUNTER_ID),
    CONSTRAINT UQ_USER_BOOK_RATING UNIQUE (USER_ID, BOOK_ENCOUNTER_ID)
);


DROP TABLE IF EXISTS USER_BOOKSHELF;
CREATE TABLE USER_BOOKSHELF (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    BOOK_ENCOUNTER_ID INT NOT NULL,
    ADDED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NOTES TEXT,
    STATUS ENUM('ACTIVE', 'REMOVED') DEFAULT 'ACTIVE',
    
    FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID),
    FOREIGN KEY (BOOK_ENCOUNTER_ID) REFERENCES BOOK_ENCOUNTER(BOOK_ENCOUNTER_ID),
    
    UNIQUE KEY UNIQUE_USER_BOOK (USER_ID, BOOK_ENCOUNTER_ID)
);
