use bookwise;

DROP TABLE IF EXISTS BOOK_WISE_USER;
CREATE TABLE BOOK_WISE_USER(
    USER_ID INT(11) NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(100) DEFAULT NULL,
    USER_PASSWORD  VARCHAR(100) DEFAULT NULL,
    AGE INT(11) DEFAULT NULL,
    GANDER  VARCHAR(10) DEFAULT NULL,
    MAIN_LANGUAGE VARCHAR(10) DEFAULT NULL,
    USER_EMAIL VARCHAR(50) DEFAULT NULL,
    USER_PHONE_NUMBER VARCHAR(50) DEFAULT NULL,
    USER_TYPE VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (USER_ID)
);

DROP TABLE IF EXISTS AUTHORITY;
CREATE TABLE AUTHORITY (
    AUTHORITY_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHORITY_NAME VARCHAR(255) NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID)
);

DROP TABLE IF EXISTS USER_AUTHORITY;
CREATE TABLE USER_AUTHORITY (
    USER_ID INT,
    AUTHORITY_ID INT,
    PRIMARY KEY (USER_ID, AUTHORITY_ID),
    FOREIGN KEY (USER_ID) REFERENCES BOOK_WISE_USER(USER_ID),
    FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY(AUTHORITY_ID)
);

INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);  -- Assuming USER_ID 1 and AUTHORITY_ID 1 for ROLE_USER

DROP TABLE IF EXISTS BOOK_ENCOUNTER;
CREATE TABLE BOOK_ENCOUNTER (
    BOOK_ENCOUNTER_ID INT(11) NOT NULL AUTO_INCREMENT,
    BOOK_TITLE VARCHAR(255) DEFAULT NULL,
    BOOK_AUTHOR VARCHAR(255) DEFAULT NULL,
    BOOK_ISBN_NUMBER VARCHAR(50) DEFAULT NULL,
    BOOK_PRICE VARCHAR(50) DEFAULT NULL,
    BOOK_PAGE_NUMBER VARCHAR(50) DEFAULT NULL,
    BOOK_CATEGORY VARCHAR(100) DEFAULT NULL,
    PUBLICATION_DATE DATE DEFAULT NULL,
    BOOK_LANGUAGE VARCHAR(50) DEFAULT NULL,
    BOOK_DESCRIPTION TEXT DEFAULT NULL,
    PDF_PATH VARCHAR(255) DEFAULT NULL,
    FRONT_PAGE_IMAGE_PATH VARCHAR(255) DEFAULT NULL,
    UPLOADED_BY_NAME VARCHAR(255) DEFAULT NULL,
    UPDATED_BY_ID VARCHAR(255) DEFAULT NULL,
    UPLOADED_TIME TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (BOOK_ENCOUNTER_ID)
);

