use bookwise;

DROP TABLE IF EXISTS BOOK_WISE_USER;
CREATE TABLE BOOK_WISE_USER(
    USER_ID INT(11) NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(100) DEFAULT NULL,
    USER_PASSWORD  VARCHAR(100) DEFAULT NULL,
    AGE INT(11) DEFAULT NULL,
    GANDER  VARCHAR(10) DEFAULT NULL,
    MAIN_LANGUAGE VARCHAR(10) DEFAULT NULL,
    USER_EMAIL VARCHAR(50) DEFAULT NULL,
    USER_PHONE_NUMBER VARCHAR(50) DEFAULT NULL,
    AUTHORITIES VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (USER_ID)
);